### ISSUE TITLE
Vary font boldness for viewed/unviewed/updated posts

### ISSUE THREAD

**Issue by spencerhitch** [knagra/farnsworth#78]
If I look at the CZ folder in my gmail inbox and defocus my eyes I can still glean information from the page.

I shouldn't have to read anything to determine the status of a thread. For example font could be emboldened on threads I haven't read at all, numbers could be emboldened for threads that I have read but that have new posts in them, and threads that I have read entirely should just be regular font. 

I think this one UX change would massively increase the amount of usage farnsworth gets. Currently there's no visual effect of having read through threads. People can't spend time on farnsworth and accomplish anything that's reflected in their view of the site.

**Comment by naderm** [comment]
Done by Connor in aedb0c3650390a3ebf6c1c957c7c96b33830a58f

Thanks @cwlbraa!
