### ISSUE TITLE
Release cycle / "stable" release?

### ISSUE THREAD

**Issue by folz** [knagra/farnsworth#82]
Hey - current toad looking to improve on some things. Do you have any sort of release cycle? I've forked farnsworth and am pulling in your changes, but it'd be nice to cherry-pick each release, instead of as commits happen.

**Comment by naderm** [comment]
Our current cycle is a rolling update where we currently deploy directly from the master branch. Our update script within docker is literally `git pull` (Plus restarting the httpd and updating the db and static files).

If you fork our code and develop on your own branch, I'm happy to pull and changes and fix any merge conflicts that may arise. Things are a bit hectic as I've been adding features as the house has been requesting them, but that should settle down in the next few days.

**Comment by folz** [comment]
Hmm, alright. Can you drop me a line? My facebook username is the same as my github one, or my email address is my first name @ my full name .com.

**Comment by naderm** [comment]
Emailed
